### ISSUE TITLE
not existing directory

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-repo-tool#18]
Using the `3a002fe05561661a63fdee1632334cba39474647` (current master), I am getting the following error:

```
cardano-repo-tool update-hash -r cardano-db-sync
Updating cardano-db-sync/cabal.project ...
cardano-repo-tool: .git/modules/ext/cardano-db-sync.git: changeWorkingDirectory: does not exist (No such 
file or directory)
```

**Comment by erikd** [comment]
cardano-repo-tool does not support git submodules.

**Comment by coot** [comment]
in `cardano-haskell` the only submodule we have is `cardano-repo-tool` itself:
```
git submodule 
+3a002fe05561661a63fdee1632334cba39474647 cardano-repo-tool (remotes/origin/HEAD)
```

**Comment by erikd** [comment]
That one submodule too many.

`cardano-repo-tool` was never designed to work in the presence of submodules.

**Comment by coot** [comment]
It's been there since the beginning of `cardano-haskell`, maybe @dcoutts knows how to fix this.

**Comment by coot** [comment]
actually it's not a problem with `cardano-haskell` but with `cardano-benchmarks` which includes submodules: https://github.com/input-output-hk/cardano-benchmarking/issues/107

**Comment by erikd** [comment]
CRT was a rough hack whipped up in a day. At there time there were no git submodules in use. The fact that it does not work does not surprise me, because this was never tested.

**Comment by coot** [comment]
I am closing, as this is a known limitation of `CRT`.
